# Generated by Django 5.2.1 on 2025-05-11 18:45

import django.db.models.deletion
import guests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[guests.models._validate_phone])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('block', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GateAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('open', 'Open Gate'), ('close', 'Close Gate')], editable=False, max_length=10)),
                ('status', models.CharField(choices=[('allowed', 'Allowed'), ('denied', 'Denied')], editable=False, max_length=10)),
                ('guest_access', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to='guests.guestaccess')),
            ],
        ),
    ]
